/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: [
      'upload.wikimedia.org',
      'www.sbi.co.in',
      'www.hdfcbank.com',
      'www.icicibank.com',
      'www.pnbindia.in',
      'www.bankofbaroda.in',
      'www.canarabank.com',
      'www.unionbankofindia.co.in',
      'www.axisbank.com',
      'www.kotak.com',
      'www.indusind.com',
      'www.bankofindia.co.in',
      'www.indianbank.in',
      'www.centralbankofindia.co.in',
      'www.ucobank.com',
      'www.bankofmaharashtra.in',
      'www.psbindia.co.in',
      'www.iob.in',
      'www.idbibank.in',
      'www.yesbank.in',
      'www.federalbank.co.in',
      'www.rblbank.com',
      'www.nainitalbank.co.in',
      'www.karnatakabank.com',
      'www.cityunionbank.com',
      'www.southindianbank.com',
      'www.tmb.in',
      'www.dcbbank.com',
      'www.bandhanbank.com',
      'www.csb.co.in',
      'www.dhanbank.com',
      'www.jkbank.net',
      'www.idfcfirstbank.com',
      'www.aubank.in',
      'www.equitasbank.com',
      'www.ujjivansfb.in',
      'www.esafbank.com',
      'www.fincarebank.com',
      'www.janabank.com',
      'www.nesfb.in',
      'www.shivalikbank.com',
      'www.unitysmallfinancebank.in',
      'www.utkarsh.bank',
      'www.suryodaybank.com',
      'www.capitalbank.in',
      'www.airtel.in',
      'www.paytm.com',
      'www.finobank.com',
      'www.jio.com'
    ],
  },
};

export default nextConfig; 